pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        stage ('Clone Repo'){
            steps {
                dir('prototype2') {
                    sh "git clone https://github.com/jjinnm4real/testRepo.git /1.3/MICA_L0/Test1."
                }    
            }
        }
        stage ('Build') {
            steps {
                dir('prototype2') {
                    bat "dir.bat"
                    

                }    
            }
        }
        
    }
    
}    
