pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        
        stage ('Build') {
            steps {
                dir('prototype2') {
                    bat "dir.bat"
                    

                }    
            }
        }
        
    }
    
}    
