pipeline{
    agent any
    stages {
        stage ('Cleanup') {
            steps {
                deleteDir()
            }            
        }
        stage ('Clone Repo'){
            steps {
                dir('TestRepo') {
                    sh "git clone /Test1"
                }    
            }
        }
        stage ('Build') {
            steps {
                dir('testRepo') {
                    bat "dir.bat"
                    

                }    
            }
        }
        
    }
    
}    
